#don't alter
max.poll.records=1
max.poll.interval.ms=900000
session.timeout.ms=30000
heartbeat.interval.ms=10000
auto.offset.reset=earliest
#alter anymore
bootstrap.servers=server:9092
#bootstrap.servers=server:60000
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
