version: 2
challenge:
  challenge_class_file: ProcessHub/bci_competition/challenge/MI/ChallengeMI.py
  challenge_class_name: ChallengeMI

# 所有预定义message,message_key
message_key_topic_dict:
  # 结果报告(对应于MessageKeyEnum.REPROT.value): 默认topic
  report: null
  algorithm_closed: null